name: Create Release with ZIP

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0

permissions:
  contents: write  # Required to create releases

jobs:
  build-zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set ZIP filename
        id: zip_name
        run: |
          ZIP_NAME="sit-theme-${{ github.ref_name }}.zip"
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          # Create ZIP with dynamic name, exclude unnecessary files
          zip -r "${{ steps.zip_name.outputs.zip_name }}" . \
            -x "*.git*" \
               ".editorconfig" \
               "SECURITY.md" \
               ".github/*" \
               "README.md" \
               "LICENSE" \
               ".gitignore"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip_name.outputs.zip_name }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 📦 Theme Release: ${{ github.ref_name }}
            
            This release includes the theme files packaged as a ZIP for easy deployment.

            > Generated automatically by GitHub Actions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
