name: Create Release with ZIP

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0

permissions:
  contents: write

jobs:
  build-zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set folder and ZIP names
        id: names
        run: |
          THEME_FOLDER="sit-theme"
          ZIP_NAME="sit-theme-${{ github.ref_name }}.zip"
          echo "theme_folder=$THEME_FOLDER" >> $GITHUB_OUTPUT
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Create theme folder and copy files
        run: |
          mkdir -p ${{ steps.names.outputs.theme_folder }}

          # Copy all files/folders except those you want to exclude
          # Adjust this list as needed
          find . -mindepth 1 -maxdepth 1 \
            ! -name '.git' \
            ! -name 'node_modules' \
            ! -name '*.zip' \
            ! -name '.github' \
            ! -name 'README.md' \
            ! -name 'LICENSE' \
            ! -name '.gitignore' \
            -exec cp -r {} ${{ steps.names.outputs.theme_folder }} \;

      - name: Create ZIP archive
        run: |
          zip -r "${{ steps.names.outputs.zip_name }}" ${{ steps.names.outputs.theme_folder }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.names.outputs.zip_name }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 📦 Theme Release: ${{ github.ref_name }}
            
            Theme packaged as \`${{ steps.names.outputs.zip_name }}\` for easy deployment.
            
            Extract to get a folder named \`sit-theme\`.

            > Generated automatically by GitHub Actions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
